spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/todos-db?currentSchema=public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      indent_output: true
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
